include(
    "presentation:api",
    "presentation:support:auth",
    "core",
    "domain",
    "gateway:rdb",
    "gateway:oauth",
    "support:yaml",
    "support:jwt",
    "support:logging",
    "support:utils",
)
